[package]
name = "token_bug_example"
version = "0.1.0"
authors = ["francosasieta <fsasieta@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
